### ISSUE TITLE
Despliegue en netlify o Vercel

### ISSUE THREAD

**Issue by rrrguez** [ULL-MII-SYTWS-2425/intro2sd-rebeca-rodriguez-alu0101394763#4]

**Comment by crguezl** [comment]
Already approved your requests to install vercel and netlify in the org

**Comment by crguezl** [comment]
@rrrguez  Buen trabajo. 

Siempre que un repo tiene un website asociado se debe en la sección "about" del repo de la asignación en la sección "Website"  haz click en "Use your GitHub Pages website". Añádelo cuando puedas

**Comment by rrrguez** [comment]
Hola, @crguezl 

Gracias por su apunte. Lo acabo de añadir. :-)

**Comment by crguezl** [comment]
@rrrguez 

No se porqué no me está apareciendo el perrito en el 404

<img width="1689" alt="Captura de pantalla 2024-10-26 a las 14 50 08" src="https://github.com/user-attachments/assets/7a7a2103-4b98-490d-8c52-9781c7255a71">

**Comment by rrrguez** [comment]
@crguezl 

He localizado el error. La rama `gh-pages` no contaba con la versión actualizada del 404.

Lo acabo de arreglar. Ahora sí debería visualizarse la imagen de perrito.

![sample](https://github.com/user-attachments/assets/d49daed0-1629-4ea9-ab26-5f8efe66267c)

**Comment by crguezl** [comment]
@rrrguez cuando se sigue el enlace de las colecciones de ejemplo el enlace falla y sale un gatito:

<img width="1084" alt="Captura de pantalla 2024-10-26 a las 22 33 33" src="https://github.com/user-attachments/assets/cfc58f5c-a566-4d94-ae9a-9f1bbac6ce92">

Esto es por que en el código liquid dice:

```liquid
A continuación, se muestran los contenidos de la colección `examples`:

{%for example in site.examples %}
  <h2><a href="{{ example.url }}">{{ example.title }}</a></h2>
  <p>{{ example.description }}</p>
{% endfor %}
```

y creo que debería decir:

```liquid
A continuación, se muestran los contenidos de la colección `examples`:

{%for example in site.examples %}
  <h2><a href="{{ site.baseurl }}/{{ example.url }}">{{ example.title }}</a></h2>
  <p>{{ example.description }}</p>
{% endfor %}
```

**Comment by rrrguez** [comment]
Arreglado el bug realizando las modificaciones indicadas :+1:

![Opera Instantánea_2024-11-01_163052_ull-mii-sytws-2425 github io](https://github.com/user-attachments/assets/8f5a42bd-a75a-4e66-a8ff-16dbf0729f55)
